import nodemailer from "nodemailer";
import { logger } from "../utils/logger.js";

let transporter = null;

const getTransporter = () => {
  if (!transporter) {
    transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST || "smtp.mailtrap.io",
      port: Number(process.env.EMAIL_PORT) || 2525,
      auth: {
        user: process.env.EMAIL_USER || "",
        pass: process.env.EMAIL_PASSWORD || ""
      }
    });
  }
  return transporter;
};

export const sendEmail = async ({ to, subject, html, text }) => {
  try {
    if (!process.env.EMAIL_USER || process.env.EMAIL_USER === "mock_user") {
      logger.info(`[Email Service (Simulated)] To: ${to} | Subject: "${subject}"`);
      return { success: true, simulated: true };
    }

    const mailer = getTransporter();
    const info = await mailer.sendMail({
      from: process.env.EMAIL_FROM || '"YĀTRI Travel" <no-reply@yatri.travel>',
      to,
      subject,
      text,
      html
    });

    logger.info(`Email successfully dispatched: ${info.messageId}`);
    return { success: true, messageId: info.messageId };
  } catch (error) {
    logger.error("Failed to send email:", error);
    return { success: false, error: error.message };
  }
};

export const sendSOSNotificationEmail = async ({ to, travelerName, location, time }) => {
  const subject = `⚠️ URGENT SOS ALERT: ${travelerName} has triggered an emergency on YĀTRI`;
  const html = `
    <div style="font-family: Arial, sans-serif; padding: 20px; background-color: #fee2e2; border-radius: 8px;">
      <h2 style="color: #991b1b;">⚠️ Emergency SOS Alert</h2>
      <p>Your emergency contact <strong>${travelerName}</strong> has triggered an urgent SOS on the YĀTRI travel safety network.</p>
      <div style="background-color: white; padding: 15px; border-radius: 6px; border-left: 4px solid #ef4444;">
        <p><strong>Time:</strong> ${time}</p>
        <p><strong>Coordinates:</strong> Lat: ${location.lat}, Lng: ${location.lng}</p>
        <p><strong>Address:</strong> ${location.address || "Live location coordinates recorded"}</p>
        <p><a href="https://maps.google.com/?q=${location.lat},${location.lng}" target="_blank" style="color: #2563eb; font-weight: bold;">View Live Location on Google Maps &rarr;</a></p>
      </div>
      <p style="margin-top: 15px; font-size: 12px; color: #6b7280;">This is an automated safety alert generated by YĀTRI Smart Safety Center.</p>
    </div>
  `;
  return sendEmail({ to, subject, html, text: `SOS Alert for ${travelerName} at Lat: ${location.lat}, Lng: ${location.lng}` });
};
